[tool.poetry]
name = "adk-research"
version = "0.1.0"
description = ""
authors = ["ianchen-tech <ianchentech@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
google-adk = ">=1.7.0,<2.0.0"
litellm = ">=1.74.7,<2.0.0"
pandas = "^2.3.2"
google-genai = "^1.31.0"
chromadb = "^1.0.20"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
